config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "profiles#index"
  resources :profiles do
    resources :favorites, only: [:create, :destroy]
    resources :ratings, only: [:new, :create, :edit, :update]
  end
  resources :users, only: [:edit, :update] do
    get :favorites, on: :collection
  end
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]
  resources :tags do
    get "profiles", to: "profiles#search"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :profile

  validates_uniqueness_of :profile_id, scope: :user_id
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :profile
  belongs_to :room
end

app/models/profile.rb
class Profile < ApplicationRecord
  mount_uploader :image, ImageUploader

  belongs_to :user
  has_many :room_users, dependent: :destroy
  has_many :rooms, through: :room_users
  has_many :messages, dependent: :destroy
  has_many :profile_tags, dependent: :destroy
  has_many :tags, through: :profile_tags
  has_many :favorites, dependent: :destroy
  has_many :ratings, dependent: :destroy

  validates :nickname, presence: true

  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags

    old_tags.each do |old|
      self.tags.delete Tag.find_by(tag_name: old)
    end

    new_tags.each do |new|
      new_profile_tag = Tag.find_or_create_by(tag_name: new)
      self.tags << new_profile_tag
    end
  end
end

app/models/profile_tag.rb
class ProfileTag < ApplicationRecord
  belongs_to :profile
  belongs_to :tag
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :profile
  validates :rate, numericality: {less_than_or_equal_to: 5, greater_than_or_equal_to: 1}

end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users, dependent: :destroy
  has_many :profiles, through: :room_users
  has_many :messages, dependent: :destroy
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :profile
  belongs_to :room
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :profile_tags, dependent: :destroy
  has_many :profiles, through: :profile_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile
  has_many :favorites, dependent: :destroy
  has_many :ratings, dependent: :destroy
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_profile

  def create
    unless @profile.user_id == current_user.id
      @favorite = Favorite.create(user_id: current_user.id, profile_id: @profile.id)
    end
  end

  def destroy
    @favorite = Favorite.find_by(user_id: current_user.id, profile_id: @profile.id)
    @favorite.destroy
  end

  private

  def set_profile
    @profile = Profile.find(params[:profile_id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action :authenticate_user!, only: [:create]

  def create
    if RoomUser.where(profile_id: current_user.id, room_id: params[:message][:room_id]).present?
      @message = Message.create!(params.require(:message).permit(:profile_id, :message, :room_id).merge(profile_id: current_user.id))
      redirect_to room_path(@message.room_id)
    else
      flash[:alert] = "メッセージを送信できませんでした"
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  before_action :contributor_confirmation, only: [:edit, :destroy]

  def index
    @profiles = Profile.order("created_at DESC")
    @tag_list = Tag.all
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
    tag_list = params[:profile][:tag_name].split(nil)
    if @profile.save
      @profile.save_tag(tag_list)
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @profiles = Profile.all
    @profile_tags = @profile.tags
    favorites = Favorite.where(user_id: current_user.id).order(created_at: :desc).pluck(:profile_id)
    @favorite_list = Profile.find(favorites)
    @rating = Rating.find_by(user_id: current_user.id, profile_id: @profile.id)
    @sendUser = RoomUser.where(profile_id: current_user.id)
    @receiveUser = RoomUser.where(profile_id: @profile.id)

    unless @profile.user_id == current_user.id
      @sendUser.each do |su|
        @receiveUser.each do |ru|
          if su.room_id == ru.room_id
            @isRoom = true
            @roomId = su.room_id
          end
        end
      end
      unless @isRoom
        @room = Room.new
        @roomUser = RoomUser.new
      end
    end
  end

  def edit
    @tag_list = @profile.tags.pluck(:tag_name).join(', ')
  end

  def update
    tag_list = params[:profile][:tag_name].split(' ')
    @profile.update(profile_params)
    if @profile.save
      @profile.save_tag(tag_list)
      redirect_to profile_path(@profile.id)
    else
      render :edit
    end
  end

  def destroy
    @profile.destroy
    redirect_to root_path
  end

  def search
    @tag = Tag.find(params[:tag_id])
    @profiles = @tag.profiles.all
  end

  private
  def profile_params
    params.require(:profile).permit(:image, :nickname, :comment, :content, :twitter, :instagram ).merge(user_id: current_user.id)
  end

  def set_profile
    @profile = Profile.find(params[:id])
  end

  def contributor_confirmation
    unless current_user.id == @profile.user_id
      redirect_to root_path
    end
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_profile, only: [:edit, :update]
  before_action :set_rating, only: [:edit, :update]

  def new
    @rating = Rating.new
  end

  def create
    @rating.create(rating_params)
    if @rating.save
      redirect_to profile_path(@profile.id)
    else
      render :new
    end
  end

  def edit
  
  end

  def update
    @rating.update(rating_params)
    if @rating.save
      redirect_to profile_path(@profile.id)
    else
      render :edit
    end
  end

  private

  def set_rating
    @rating = Rating.find(params[:id])
  end

  def set_profile
    @profile = Profile.find(params[:profile_id])
  end

  def rating_params
    params.require(:rating).permit(:rate).merge(user_id: current_user.id, profile_id: @profile.id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  before_action :authenticate_user!

  def create
    @room = Room.create
    @roomUser1 = RoomUser.create(room_id: @room.id, profile_id: current_user.id)
    @roomUser2 = RoomUser.create(params.require(:room_user).permit(:profile_id, :room_id).merge(room_id: @room.id))
    redirect_to room_path(@room.id)
  end

  def show
    @room = Room.find(params[:id])
    if RoomUser.where(profile_id: current_user.id, room_id: @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @roomUsers = @room.room_users
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/_favorite.html.erb
<% if !Favorite.exists?(user_id: current_user.id, profile_id: profile.id) %>
  <%= link_to profile_favorites_path(profile.id), method: :post, remote: true, class:"favorite-btn" do %>
    <button><span class="favorite-count1">お気に入りに追加</span></button>
  <% end %>
<% else %>
  <%= link_to profile_favorite_path(profile_id: profile.id, id: profile.favorites[0].id), method: :delete, remote: true, class:"favorite-btn" do %>
    <button><span class="fafvorite-count2">お気に入りを解除</span></button>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
$('#favorite_<%= @profile.id %>').html("<%= j(render partial: 'favorites/favorite', locals: { profile: @profile }) %>")

app/views/favorites/destroy.js.erb
$('#favorite_<%= @profile.id %>').html("<%= j(render partial: 'favorites/favorite', locals: { favorite: @favorite }) %>");

app/views/profiles/edit.html.erb
<%= render "shared/second-header"%>

<%= form_with model: @profile, local: true do |f| %>

<div class='registration-main'>
  <div class='form-wrap'>
    <div class='form-header'>
      <h1 class='form-header-text'>
        プロフィール入力
      </h1>
    </div>

    <%= render 'shared/error_messages', model: f.object %>

    <div class="img-upload">
      <div class="click-upload">
        <% if @profile.image? %>
          <%= image_tag @profile.image.url, :size => '300x300' %>
        <% else %>
          <%= image_tag "/assets/default-user-icon.png", :size => '300x300' %>
        <% end %>
        <div class="upload-btn">
          <button type="button" class="btn-profile-image">
            <%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png,image/heic' %>
          </button>
        </div>
      </div>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">ニックネーム</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :nickname, class:"input-default", id:"nickname", maxlength:"40" %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">固定コメント</label>
      </div>
      <%= f.text_area :comment, class:"input-default", id:"comment", maxlength:"40" %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">自由記載欄</label>
      </div>
      <%= f.text_area :content, class:"input-default", id:"content", placeholder:"コメント・自己紹介など", rows:"5" %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">SNSアカウント登録</label>
      </div>
      <div class='form-text-wrap'>
        <label class="form-text">twitter</label>
      </div>
      <%= f.text_field :twitter, class:"input-default", id:"twitter", placeholder:"URLを入力してください" %>
      <div class='form-text-wrap'>
        <label class="form-text">instagram</label>
      </div>
      <%= f.text_field :instagram, class:"input-default", id:"instagram", placeholder:"URLを入力してください" %>
    </div>
    <div class="form-group">
      <div class="form-text-wrap">
        <label class="form-text">ハッシュタグ</label>
      </div>
      <%= f.text_field :tag_name, class:"input-default", id:"tag_name", placeholder:"例) #仕事 #恋愛 #人間関係"%>
      <div class="form-text-wrap">
        <label class="form-text">※スペースを入力すると複数のタグ付けができます</label>
      </div>
    </div>
    <div class='register-btn'>
      <%= f.submit "登録" ,class:"register-red-btn" %>
    </div>
  </div>
</div>
<% end %>

app/views/profiles/index.html.erb
<%= render partial: "shared/header", locals: {profiles: @profiles} %>

<div class='main'>

  <div class='call-contents'>
    <h2 class='call-title'>
      気軽に相談してみよう！
    </h2>
  </div>

  <div class='user-lists'>
    <div class='login-user'>
      <h2 class='login-user-title'>
        全体のユーザー
      </h2>
      <div class='user-list'>
        <% @profiles.each do |profile| %>
          <div class='user-wrapper'>
            <%= link_to profile_path(profile.id) do %>
              <% if profile.image? %>
                <%= image_tag profile.image.url, :size => '200x200' %>
              <% else %>
                <%= image_tag "/assets/default-user-icon.png", :size => '200x200' %>
              <% end %>
              <div class='user-body'>
                <div class='header_comment'>
                  <%= profile.comment %>
                </div>
                <div class='user_name'>
                  <%= profile.nickname %>
                </div>
                <div class='tag-list'>
                  <%= profile.tags.map(&:tag_name).join(' ') %>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<%= render "shared/second-header"%>

<%= form_with model: @profile, local: true do |f| %>

<div class='registration-main'>
  <div class='form-wrap'>
    <div class='form-header'>
      <h1 class='form-header-text'>
        プロフィール入力
      </h1>
    </div>

    <%= render 'shared/error_messages', model: f.object %>

    <div class="img-upload">
      <div class="click-upload">
        <% if @profile.image? %>
          <%= image_tag @profile.image.url, :size => '300x300' %>
        <% else %>
          <%= image_tag "/assets/default-user-icon.png", :size => '300x300' %>
        <% end %>
        <div class="upload-btn">
          <button type="button" class="btn-profile-image">
            <%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png' %>
          </button>
        </div>
      </div>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">ニックネーム</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :nickname, class:"input-default", id:"nickname", maxlength:"40" %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">固定コメント</label>
      </div>
      <%= f.text_area :comment, class:"input-default", id:"comment", maxlength:"40" %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">自由記載欄</label>
      </div>
      <%= f.text_area :content, class:"input-default", id:"content", placeholder:"コメント・自己紹介など", rows:"5" %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">SNSアカウント登録</label>
      </div>
      <div class='form-text-wrap'>
        <label class="form-text">・twitter</label>
      </div>
      <%= f.text_field :twitter, class:"input-default", id:"twitter", placeholder:"URLを入力してください" %>
      <div class='form-text-wrap'>
        <label class="form-text">・instagram</label>
      </div>
      <%= f.text_field :instagram, class:"input-default", id:"instagram", placeholder:"URLを入力してください" %>
    </div>
    <div class="form-group">
      <div class="form-text-wrap">
        <label class="form-text">ハッシュタグ</label>
      </div>
      <%= f.text_field :tag_name, class:"input-default", id:"tag_name", placeholder:"例) #仕事 #恋愛 #人間関係"%>
      <div class="form-text-wrap">
        <label class="form-text">※スペースを入力すると複数のタグ付けができます</label>
      </div>
    </div>
    <div class='register-btn'>
      <%= f.submit "登録" ,class:"register-red-btn" %>
    </div>
  </div>
</div>
<% end %>

app/views/profiles/search.html.erb
<%= render "shared/second-header"%>

<div class="main">

  <div class='call-contents'>
    <h2 class='call-title'>
      <%= @tag.tag_name %>の検索結果
    </h2>
  </div>

  <div class='user-lists'>
    <div class='user-list'>
      <% @profiles.each do |profile| %>
        <div class='user-wrapper'>
          <%= link_to profile_path(profile.id) do %>
            <% if profile.image? %>
              <%= image_tag profile.image.url, :size => '200x200' %>
            <% else %>
              <%= image_tag "/assets/default-user-icon.png", :size => '200x200' %>
            <% end %>
            <div class='user-body'>
              <div class='header_comment'>
                <%= profile.comment %>
              </div>
              <div class='user_name'>
                <%= profile.nickname %>
              </div>
              <p class='rating-star'>
                <%= image_tag "star-on.png" %>
              </p>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<%= render partial: "shared/header", locals: {profiles: @profiles} %>

<div class='user-show'>

  <div class="rating-form-link">
    <%#= link_to "評価画面へ", new_profile_rating_path(@profile.id), class:"registration-rating" %>
  
  <div class='user-profile'>
    <div class="favorite-btn", id="favorite_<%= @profile.id %>">
      <% unless current_user.id == @profile.user_id %>
        <%= render "favorites/favorite", profile: @profile %>
      <% end %>
    </div>
    <% if @profile.image? %>
      <%= image_tag @profile.image.url, :size => '400x400' %>
    <% else %>
      <%= image_tag "/assets/default-user-icon.png", :size => '400x400' %>
    <% end %>
    <p class='user-name'>
    <%= @profile.nickname %>
    </p>
    <p class='profile-comment'>
    <%= @profile.content %>
    </p>
    <div class='sns-link'>
      <ul class="snsbtn">
        <% if @profile.twitter? %>
          <li><a href="@profile.twitter" class="flowbtn6 fl_tw1"><i class="fab fa-twitter"></i></a></li>
        <% end %>
        <% if @profile.instagram? %>
          <li><a href="@profile.instagram" class="flowbtn6 insta_btn6"><i class="fab fa-instagram"></i></a></li>
        <% end %>
      </ul>
    </div>
    <div class='tag-list'>
      <% @profile_tags.each do |tag| %>
        <%= link_to tag.tag_name, tag_profiles_path(tag_id: tag.id) %>
      <% end %>
    </div>
    <div class='chat-start-btn'>
      <% unless current_user.id == @profile.user_id %>
        <% if @isRoom == true %>
          <%= link_to "メッセージを送る", room_path, class:"chat-start-red-btn" %>
        <% else %>
          <%= form_with model: @room, lpcal: true do |f| %>
            <%= fields_for @roomUser do |r| %>
              <%= r.hidden_field :profile_id, value: @profile.user_id %>
            <% end %>
            <%= f.submit "メッセージを送る", class:"chat-start-red-btn" %>
         <% end %>
        <% end %>
      <% end %>
    </div>
    

    <div class='rating-star'>
    </div>
    <div class="edit-delete">
      <%= link_to "プロフィールの編集", edit_profile_path(current_user.id), method: :get, class: "user-edit-btn" %>
      <p class="or-text">or</p>
      <%= link_to "削除", profile_path(current_user.id), method: :delete, class:"user-destroy" %>
    </div>
  </div>

  <div class="favorite-list">
    <% if current_user.id == @profile.user_id %>
      <p class="favorite-list-title">お気に入りのユーザー</p>
      <% if @favorite_list.present? %>
        <% @favorite_list.each do |profile| %>
          <div class="favorite-user-profile">
            <%= link_to image_tag profile.image.url, :size => '50x50'%>
            <%= link_to profile.nickname, profile_path(profile.id) %>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/ratings/edit.html.erb
<%= render "shared/second-header"%>

app/views/ratings/new.html.erb
<%= render "shared/second-header"%>

<%= form_with model: @rating, local: true do |f| %>

<div class='form-wrap'>
  <div class='form-header'>
    <h1 class='form-header-text'>
      評価入力
    </h1>
  </div>

  <div id="rating_form">
    <%= f.hidden_field :rate %>
  </div>
</div>
<% end %>

<script>
  $('#rating_form').raty({
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    starHalf: "<%= asset_path('star-half.png') %>",
    scoreName: 'rating[rate]',
    half: true,
  });
</script>

app/views/rooms/show.html.erb
<%= render "shared/second-header"%>

<div class="chat-body">
  

  <div class="chats">
    <div class="chat">
      <% if @messages.present? %>
        <% @messages.each do |m| %>
          <div class="chat-box">
            <div class="chat-face">
              <%= image_tag m.profile.image.url, :size => '100x100', class:"user-image" %>
            </div>
            <div class="chat-user-name">
              <%= m.profile.nickname %>
            </div>
            <div class="chat-hukidashi"> <strong><%= m.message %></strong> <br>
              <%= m.created_at.strftime("%Y-%m-%d %H:%M")%>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<div class="chat-form">
  <div class="posts">
    <%= form_with model: @message, local: true do |f| %>
      <%= f.text_field :message, placeholder: "メッセージを入力して下さい" , size: 70, class:"form-text-field" %>
      <%= f.hidden_field :room_id, value: @room.id %>
      <%= f.submit "送信",class:"form-submit"%>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<%= render "shared/second-header"%>

<%= form_with model: current_user, local: true do |f|%>

<div class='form-wrap'>
  <div class='form-header'>
    <h1 class='form-header-text'>
      ユーザー情報入力
    </h1>
  </div>

  <%= render 'shared/error_messages', model: f.object %>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">メールアドレス</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.email_field :email, class:"input-default", id:"email", placeholder:"PC・携帯どちらでも可", autofocus: true %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">パスワード</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.password_field :password, class:"input-default", id:"password", placeholder:"6文字以上の半角英数字" %>
    <p class='info-text'>※英字と数字の両方を含めて設定してください</p>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">パスワード(確認)</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.password_field :password_confirmation, class:"input-default", id:"password-confirmation", placeholder:"同じパスワードを入力して下さい" %>
  </div>
  <div class='register-btn'>
    <%= f.submit "登録" ,class:"register-red-btn" %>
  </div>
<% end %>