config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "profiles#index"
  resources :profiles do
    resources :favorites, only: [:create, :destroy]
    resources :ratings, only: [:new, :create, :edit, :update]
  end
  resources :users, only: [:edit, :update] do
    get :favorites, on: :collection
  end
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]
  resources :tags do
    get "profiles", to: "profiles#search"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :profile

  validates_uniqueness_of :profile_id, scope: :user_id
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :profile
  belongs_to :room
end

app/models/profile.rb
class Profile < ApplicationRecord
  mount_uploader :image, ImageUploader

  belongs_to :user
  has_many :room_users, dependent: :destroy
  has_many :rooms, through: :room_users
  has_many :messages, dependent: :destroy
  has_many :profile_tags, dependent: :destroy
  has_many :tags, through: :profile_tags
  has_many :favorites, dependent: :destroy
  has_many :ratings, dependent: :destroy

  validates :nickname, presence: true

  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags

    old_tags.each do |old|
      self.tags.delete Tag.find_by(tag_name: old)
    end

    new_tags.each do |new|
      new_profile_tag = Tag.find_or_create_by(tag_name: new)
      self.tags << new_profile_tag
    end
  end
end

app/models/profile_tag.rb
class ProfileTag < ApplicationRecord
  belongs_to :profile
  belongs_to :tag
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :profile
  validates :rate, numericality: {less_than_or_equal_to: 5, greater_than_or_equal_to: 1}

end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users, dependent: :destroy
  has_many :profiles, through: :room_users
  has_many :messages, dependent: :destroy
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :profile
  belongs_to :room
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :profile_tags, dependent: :destroy
  has_many :profiles, through: :profile_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile
  has_many :favorites, dependent: :destroy
  has_many :ratings, dependent: :destroy
  
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_profile, only: [:edit, :update]
  before_action :set_rating, only: [:edit, :update]

  def new
    @rating = Rating.new
  end

  def create
    @rating.create(rating_params)
    if @rating.save
      redirect_to profile_path(@profile.id)
    else
      render :new
    end
  end

  def edit
  
  end

  def update
    @rating.update(rating_params)
    if @rating.save
      redirect_to profile_path(@profile.id)
    else
      render :edit
    end
  end

  private

  def set_rating
    @rating = Rating.find(params[:id])
  end

  def set_profile
    @profile = Profile.find(params[:profile_id])
  end

  def rating_params
    params.require(:rating).permit(:rate).merge(user_id: current_user.id, profile_id: @profile.id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  before_action :authenticate_user!

  def create
    @room = Room.create
    @roomUser1 = RoomUser.create(room_id: @room.id, profile_id: current_user.id)
    @roomUser2 = RoomUser.create(params.require(:room_user).permit(:profile_id, :room_id).merge(room_id: @room.id))
    redirect_to room_path(@room.id)
  end

  def show
    @room = Room.find(params[:id])
    if RoomUser.where(profile_id: current_user.id, room_id: @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @roomUsers = @room.room_users
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KiiteProto1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<header class='top-page-header'>
  <%= link_to image_tag("logo.png", class:"logo-icon"), "/" %>
  <div class='search-bar-contents'>
    <form class="search-form" action="#">
      <input class='input-box' placeholder='キーワードから探す'>
      <button class="search-button">
        <%= image_tag "search.png", class:"search-icon" %>
      </button>
    </form>
  </div>
  <div class='nav'>
    <ul class='lists-right'>
      <% if user_signed_in? %>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
        <% if profiles.find_by(user_id: current_user.id).nil? %>
          <li><%= link_to 'プロフィール登録', new_profile_path, class: "registration-profile" %></li>
        <% else %>
          <li><%= link_to 'マイプロフィール', profile_path(current_user.id), class: "my-profile" %></li>
        <% end %>
      <% else %>  
        <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>  
    </ul>
  </div>
</header>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("logo.png", class:"second-logo"), "/" %>
</header>